name: Publish to crates.io

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2.9.2

      - name: Run tests
        run: cargo test --all-targets

      - name: Authenticate with crates.io
        uses: crates-io/github-actions-auth@v1

      - name: Publish to crates.io
        run: cargo publish --locked
